### PR TITLE
Fix icon being not displayed on some devices

### PR DESCRIPTION
**Pull request by Vavun**
Fix icon being not displayed in settings on some devices with android 6, 7 and 7,1 (SDK 23,24,25)

### CODE REVIEW

**Comment by Vavun** [comment]
@Nanolx 
Hello again
I suggest to try this icon for microG in system settings (name: extension)
https://material.io/tools/icons/?icon=extension&style=baseline
accidentally found it on material.io , looks like main microG gmscore icon

baseline_extension_black_24dp

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <path
        android:fillColor="#000000"
        android:pathData="M20.5 11H19V7c0-1.1-0.9-2-2-2h-4V3.5C13 2.12 11.88 1 10.5 1S8 2.12 8 3.5V5H4c-1.1 0-1.99 0.9 -1.99 2v3.8H3.5c1.49 0 2.7 1.21 2.7 2.7s-1.21 2.7-2.7 2.7H2V20c0 1.1 0.9 2 2 2h3.8v-1.5c0-1.49 1.21-2.7 2.7-2.7 1.49 0 2.7 1.21 2.7 2.7V22H17c1.1 0 2-0.9 2-2v-4h1.5c1.38 0 2.5-1.12 2.5-2.5S21.88 11 20.5 11z" />
</vector>
```

**Comment by Vavun** [comment]
Another variant from 4pda community by user **MegaFon929**



```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <path
        android:fillColor="#000000"
        android:pathData="M14.5335,0.0569535 L9.43985,0.0705542 C9.24288,0.102156,9.0985,0.18001,9.06273,0.352909 L8.55771,3.75569 C7.70454,4.01856,7.0852,4.47885,6.46902,4.94163 L3.48987,3.74936 C3.23326,3.67936,2.95937,3.47486,2.64004,3.95331 L0.0871706,8.21668 C0.0372893,8.41036,0.0580599,8.56989,0.145272,8.69686 L2.93012,10.8425 C2.83047,11.6279,2.86713,12.4355,2.90092,13.2426 L0.23227,15.219 C0.005066,15.4246,0.050044,15.7049,0.087127,15.8119 L2.78493,20.2165 C2.89848,20.3411,3.04458,20.3919,3.22668,20.3608 L6.49813,19.1434 C7.12487,19.6363,7.79275,20.0492,8.52873,20.3294 L8.99269,23.3505 C9.11365,23.56,9.09564,23.8073,9.4858,23.9434 L14.6784,23.9434 C14.8701,23.8649,15.0801,23.8217,15.1137,23.4353 L15.5776,20.2729 C16.4832,19.9372,17.01,19.5277,17.6663,19.1435 L20.7121,20.3576 C21.1885,20.4803,21.2695,20.2522,21.3504,20.16 L23.8741,15.8401 C23.9395,15.7104,23.9625,15.4495,23.787,15.2191 L21.1762,13.2708 C21.1953,12.4738,21.2347,11.6899,21.1762,10.8426 L23.874,8.72511 C23.996,8.49886,23.9302,8.24834,23.874,8.10387 L21.3214,3.92514 C21.1924,3.70382,20.9206,3.64557,20.7701,3.67097 L17.6082,4.94163 C16.8967,4.38465,16.2039,3.98905,15.5197,3.67097 L14.9974,0.395711 C14.9027,0.136848,14.7173,0.0991057,14.5334,0.0570135 Z M11.8718,5.62811 C13.7255,5.60431,15.517,6.32771,16.5932,7.54186 L14.7953,9.4995 C13.2639,8.11395,9.57199,7.53593,8.30443,11.1012 C7.82376,12.9227,8.54727,14.4138,10.0518,15.2852 C11.6506,16.1862,14.0977,15.4204,14.7343,14.7492 L16.6846,16.6771 C15.8496,17.3442,12.7132,19.81,8.67011,17.6858 C6.61824,16.5517,4.69843,14.6267,5.53146,10.4485 C6.00671,8.8177,7.06262,7.50059,8.60931,6.53345 C9.62512,5.92563,10.7596,5.64239,11.8718,5.62811 Z" />
</vector>
```

**Comment by Nanolx** [comment]
Oh yes, this one looks pretty cool.

**Comment by Vavun** [comment]
UPD

Normal icon on PIE should look like this

1w

And we have this

1b

I changed `android:fillColor="#000000"` to `android:fillColor="#ffffff"` for both

Didn't check that on PIE before. At least on Nougat "ffffff" looks like the same as "000000". So this has no difference for pre PIE roms

Just keeping you informed, nothing important.

**Pull request merged**
