### PR TITLE
Separate launcher icon from main activity

### PR DESCRIPTION
**Pull request by Vavun**
Separate launcher icon from main activity so it can be disabled manualy without breaking app functional.

Some users at russian community reported that microg stop worhing after disabling main activity to hide microg from launcher (damn it is logical that it will break this activity functional !!)
In future it can be used as part of custom setting to hide launcher icon and system settings integration

### CODE REVIEW

**Comment by Vavun** [comment]
@Nanolx and if possible check this https://github.com/Nanolx/android_packages_apps_GmsCore/compare/master...Vavun:manage-acc

I think it will be better but I cant compile something at this moment.
Thanks

**Comment by Vavun** [comment]
@Nanolx I'm sorry, I made some mess. Just noticed it.
PNG should not be included.

I uploaded them for another PR for vanila microg and I dont know how they got into the master
https://github.com/microg/android_packages_apps_GmsCore/pull/738

In this case, it should be either removed or add this XML to make it have sence.
https://github.com/microg/android_packages_apps_GmsCore/blob/96e66d83c8f47d2fd8740aaa9168c7e6798eddeb/play-services-core/src/main/res/mipmap-anydpi-v26/ic_core_service_app.xml

Sorry. My bad.

**Comment by Nanolx** [comment]
No Problem, I'v merged vavun/patch-9

**Comment by Vavun** [comment]
Ok, thanks.
And what about this ?
https://github.com/Vavun/android_packages_apps_GmsCore/commit/232056421123359f3e6cdacab9bf7188676d56d2


ScreenRecord20190324025232

**Comment by Nanolx** [comment]
Looks fine to me.

**Pull request merged**
